image: node:current

stages:
 - test
 - coverage

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

.test_template: &test_definition
  stage: test
  script:
    # Install all dependencies
    - yarn install --frozen-lockfile
    # Run the tests
    - yarn test
  cache:
    key: 
      files:
        - yarn.lock
    paths:
      - .npm
      - node_modules
  artifacts:
    paths:
      - coverage
  only:
    - merge_requests
    - branches
    - tags

test_node12:
  <<: *test_definition
  image: node:12

test_node14:
  <<: *test_definition
  image: node:14

test_node15:
  <<: *test_definition
  image: node:15

coverage:
  stage: coverage
  script:
    # Upload code coverage
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  dependencies:
    - test_node15
  only:
    - branches
    - tags

