image: node:current

stages:
 - test
 - coverage
 - staging

variables:
  yarn_config_cache: "$CI_PROJECT_DIR/.yarn"

.test_template: &test_definition
  stage: test
  script:
    # Install all dependencies
    - yarn install --frozen-lockfile
    # Run the unit tests
    - yarn test
    # Attempt to build
    - yarn build
  cache:
    key: 
      files:
        - yarn.lock
    paths:
      - .yarn
      - node_modules
  artifacts:
    paths:
      - coverage
  only:
    - merge_requests
    - branches
    - tags

test_node12:
  <<: *test_definition
  image: node:12

test_node14:
  <<: *test_definition
  image: node:14

test_node15:
  <<: *test_definition
  image: node:15

deploy_staging:
  stage: staging
  script:
    - export STAGING_URL=$(npx vercel@20 --build-env REACT_APP_MQTT_ENVIRONMENT=staging --token $VERCEL_TOKEN --confirm)
    - echo "STAGING_URL=$STAGING_URL" >> build.env
  artifacts:
    reports:
      dotenv: build.env

coverage:
  stage: coverage
  script:
    # Upload code coverage
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  needs:
    - job: test_node15
      artifacts: true
  only:
    - branches
    - tags
