image: node:current

stages:
 - test
 - coverage

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

test:
  stage: test
  script:
    # Install all dependencies
    - yarn install --frozen-lockfile
    # Run the tests
    - yarn test
  cache:
    key: 
      files:
        - yarn.lock
    paths:
      - .npm
      - node_modules
  artifacts:
    paths:
      - coverage
  only:
    - merge_requests
    - branches
    - tags

coverage:
  stage: coverage
  script:
    # Upload code coverage
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  dependencies:
    - test
  only:
    - branches
    - tags

